### ISSUE TITLE
v2 or v3

### ISSUE THREAD

**Issue by ChitownWillie** [AngelGryph/MadeInHeaven_SpellPack#1]
Hey Angel,

You have both v2 and v3 listed in most recent version:

![image](https://user-images.githubusercontent.com/65503897/100344600-b30d4500-2fa6-11eb-8886-9777349af69f.png)

**Comment by AngelGryph** [comment]
Looks like I forgot to push the "publish" button, v3 has been standing here as a draft all this time. ^^
