### ISSUE TITLE
Bear's Endurance Scroll icon is blank

### ISSUE THREAD

**Issue by Endarire** [AngelGryph/MadeInHeaven_SpellPack#15]
Greetings, @AngelGryph!

The icon for a Scroll of Bear's Endurance is blank.  The spellbook icon is the _strength_ spell icon.

What say you to changing these icons to be a bear icon from Shapeshift; Bear, possibly recolored?

Thankee!

**Comment by AngelGryph** [comment]
Fixed in master.
