### ISSUE TITLE
Error installing "Revised Strength Table" on BGT

### ISSUE THREAD

**Issue by ChitownWillie** [AngelGryph/MadeInHeaven_SpellPack#2]
Installing [Revised Strength Table] [v2]
Creating 1 directory
Creating 1 directory
Creating 1 directory
Creating 1 directory
Creating 1 directory
Creating 1 directory

ERROR Installing [Revised Strength Table], rolling back to previous state
Will uninstall   0 files for [MIH_SP/SETUP-MIH_SP.TP2] component 12.
Uninstalled      0 files for [MIH_SP/SETUP-MIH_SP.TP2] component 12.
ERROR: Failure("Unknown function: check_ini")
Please make a backup of the file: SETUP-MIH_SP.DEBUG and look for support at: angel@pearlgates.net
Using Language [English]

**Comment by AngelGryph** [comment]
This component has been discontinued.
