### ISSUE TITLE
Spell restorations component installation fails

### ISSUE THREAD

**Issue by mleduque** [AngelGryph/MadeInHeaven_SpellPack#3]
If you try to install the component "Spell restorations", it fails because it can't find the `mih_sp/spell_restorations/_copy` directory. This directory doesn't exist.
Just creating an empty `_copy` directory at this location allows the installation to succeed, but you can't add an empty directory in git (it will be ignored).
Usually one would add a single useless file in a directory so it would be staged in git, but that would pollute the `override` if I  understand correctly what happens.
In that case you could instead modify `install_spell_pack` in `lib_installer.tph` to check if `%MOD_FOLDER%/%component_loc%/%spell_copy%`exists before attempting a `COPY_LARGE`?

**Comment by AngelGryph** [comment]
Good catch.  Fixed in v4 which I will be uploading soon.
