### ISSUE TITLE
Requesting Thorough Documentation as to What Each Feature Does

### ISSUE THREAD

**Issue by Endarire** [AngelGryph/MadeInHeaven_SpellPack#4]
Greetings, @AngelGryph!  Thankee for making and publicly releasing this mod!

I felt inspired by the image below to check the mod's documentation, and I found very little info in README.md and on this GitHub site.  More specifically, what do all the components do?

(Also, Project Infinity lists Made In Heaven Spell Pack 4 as "v3" and not "Made In Heaven Spell Pack v4" or somesuch.)

Thankee!

![image](https://user-images.githubusercontent.com/10439725/134280977-75f5a166-e71d-4024-ae3c-471fde3c4e21.png)

**Comment by AngelGryph** [comment]
Try the readme file in the docs folder of the mod, that is the official documentation.

I'm very sorry, but since I cannot use it at all even if I wanted to due to it being Windows only, fixing PI issues does not have a high priority for me.

**Comment by GregCampbellPresents** [comment]
@AngelGryph 
Having read this comment, I just noticed there was a docs directory!  I wish the main GitHub page would have this information or/and directed me to the docs directory for more info.  That would have solved my previous problem.

Thankee!

**Comment by GraionDilach** [comment]
For the record, the visual issue in ProjectInfinity is caused by all Made in Heaven mods having the `[metadata]` ini block starting with lowercase instead of spelling it as `[Metadata]`.
