### ISSUE TITLE
Evard's INVISIBLE Tentacles

### ISSUE THREAD

**Issue by GregCampbellPresents** [AngelGryph/MadeInHeaven_SpellPack#5]
@AngelGryph 
Greetings!

I've tried installing your spell pack and love the notion that Evard's Black Tentacles are in it.  When I cast this spell on an EET install, it shot out a black projectile that became *invisible* tentacles!  The spell still affected creatures as my Mage volunteered to walk into the area, and it wasn't a problem with spell graphics in general.  The Warlock mod's Chilling Tentacles showed as icy blue.

I used the latest release for this (Aug 4, 2021).

Thankee for fixing this!

**Comment by GregCampbellPresents** [comment]
@AngelGryph 
The Made in Heaven Spell Pack (v4) is the source of this graphical glitch on EET.  I confirmed this today by testing MIH with EET & Worldmap & DLCMerger (and Morpheus's Buff Scripts).  The same stuff happens:  The projectile is black but the tentacles from Evard's Black Tentacles are invisible.  The tentacles still hurt stuff in their AoE.

**Comment by AngelGryph** [comment]
Fixed in v5, missing bam files.
