### ISSUE TITLE
Spell Matrix

### ISSUE THREAD

**Issue by GregCampbellPresents** [AngelGryph/MadeInHeaven_SpellPack#7]
@AngelGryph 
Greetings again!

This is the same mod install as Tattoos of Power.

The Spell Matrix spell has this text on the right after casting which also seems like the same misplaced string as Tattoos of Power.  
![image](https://user-images.githubusercontent.com/52060970/137261699-b3abcc5d-9357-4be5-97a6-7959aae731c2.png)

Note this innate ability says MINOR Sequencer and not Spell Matrix.
![image](https://user-images.githubusercontent.com/52060970/137261775-136f3986-701c-4c33-8c41-5db1b0c32ba9.png)

Thankee for fixing these!

**Comment by AngelGryph** [comment]
Yeah, it's a strref difference between bgee and bg2ee, the string is correct in bgee.  Oh well, this should be an easy fix.

**Comment by AngelGryph** [comment]
Fixed in v5.
